# =============================================================================
# CTI Platform - detection rule draft generation (IOC / sample driven)
# -----------------------------------------------------------------------------
# Extends the existing actor/technique Sigma generator (app/detection_rules.py,
# left untouched) with IOC-driven network / signature outputs:
#   * Suricata rules     (validated with `suricata -T`, engine's own parser)
#   * Snort rules        (shared-compatible syntax subset; validated through
#                         Suricata's parser — Snort is not installable on the
#                         Debian 13 base image, so this is stated honestly)
#   * ModSecurity rules  (OWASP-CRS-compatible draft)
#   * Firewall / IP blocklist (plain, iptables, nftables)
#   * YARA rule          (drafted from a confirmed-malicious sample's hashes +
#                         distinctive printable strings)
# Every output is a REVIEWABLE DRAFT — never auto-deployed. Deterministic SIDs
# are derived from the IOC value so identical inputs give identical output.
# =============================================================================

from __future__ import annotations

import re
from hashlib import md5
from typing import Any

# ASCII-only (YARA rule files won't lex UTF-8 em-dashes and such).
DISCLAIMER = (
    "DRAFT - generated by Argus CTI for analyst review only. Never deploy "
    "automatically. Validate in a staging engine before production use."
)

_SID_BASE = 4_000_000  # escape the reserved <1e6 range shared with default sets

_IPV4 = re.compile(r"^\d{1,3}(\.\d{1,3}){3}$")
_IPV6 = re.compile(r"^[0-9a-fA-F:]{2,45}$")
_DOMAIN = re.compile(r"^([a-zA-Z0-9_-]+\.)+[a-zA-Z]{2,}$")
_HEX = re.compile(r"^[0-9a-fA-F]+$")


def _sid(seed: str) -> int:
    """Deterministic sid/rule-id in the public range (stable across calls)."""
    raw = int(md5(seed.encode("utf-8")).hexdigest()[:8], 16)
    return _SID_BASE + (raw % 100_000)


def _iptest(value: str) -> str | None:
    """Return '4'|'6' when the value looks like an IP, else None (honest)."""
    if _IPV4.match(value):
        return "4"
    if ":" in value and _IPV6.match(value):
        return "6"
    return None


def _yara_escape(s: str) -> str:
    # YARA string escapes: \\ \" \t \n \r and \xNN. Everything else must be
    # preceded by a backslash to be treated literally; we double any backslash
    # and any double quote, then re-tokenise so the rule lexes cleanly.
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _yara_strings(data: bytes, limit: int = 5) -> list[str]:
    """Distinctive printable ASCII run-length >= 6, deduped, caps applied."""
    runs = re.findall(rb"[ -~\t]{6,}", data)
    out: list[str] = []
    # Longer runs first -> strongest signal. Reject strings that still contain
    # YARA-hostile bytes after the printable filter (e.g. embedded '"' breaks
    # the double-quoted literal) to keep the draft guaranteed compilable.
    for run in sorted({r.decode("latin-1") for r in runs}, key=len, reverse=True):
        if len(out) >= limit:
            break
        if '"' in run:
            continue
        if "\\" in run and run.count("\\") > len(run) // 8:
            continue
        out.append(run)
    return out


def _note(marker: str, text: str, prefix: str = "#") -> str:
    # Rule files (YARA especially) refuse non-ASCII bytes; force ASCII-clean.
    clean = re.sub(r"[^\x20-\x7e]", "-", text)
    return f"{prefix} [{marker}] {clean}\n"


# --------------------------------------------------------------------------- #
# Suricata + Snort (shared-syntax subset where the engines genuinely agree)   #
# --------------------------------------------------------------------------- #

def _suricata_snort_rules(sample: dict[str, Any] | None,
                          iocs: list[dict[str, str]]) -> tuple[str, str]:
    """Network rules: IP / domain / URL / JA3 from the provided IOC set.

    File hashes cannot be matched inline in Suricata/Snort target syntax — the
    canonical form is a `filemd5:<list>` reference; we emit that rule plus the
    hash list block it must be paired with (kept honest, not guessed).
    """
    lines: list[str] = [_note("draft", "Suricata / Snort rules — " + DISCLAIMER)]
    snort: list[str] = [_note("draft", "Snort rules — " + DISCLAIMER)]
    file_hashes: dict[str, list[str]] = {"md5": [], "sha1": [], "sha256": []}
    has_net = False

    for ioc in iocs:
        itype = str(ioc.get("type", "")).lower()
        value = str(ioc.get("value", "")).strip()
        if not value:
            continue

        if itype in ("ipv4", "ipv6"):
            has_net = True
            if itype == "ipv4" and not _IPV4.match(value):
                continue
            if itype == "ipv6" and ":" not in value:
                continue
            sid = _sid(f"ip-{value}")
            rule = (
                f'alert ip $HOME_NET any -> any any '
                f'(msg:"Argus CTI - known malicious IP {value}"; '
                f'sid:{sid}; rev:1; classtype:trojan-activity; metadata:arguscti;'
                f')'
            )
            lines.append(rule)
            # Snort 2.9 uses the same net-flow header/keyword subset.
            snort.append(rule.replace("metadata:arguscti;", "").strip())

        elif itype == "domain":
            if not _DOMAIN.match(value):
                continue
            has_net = True
            sid = _sid(f"dns-{value}")
            sur = (
                f'alert dns $HOME_NET any -> any any '
                f'(msg:"Argus CTI - known malicious domain {value}"; '
                f'dns.query; content:"{value}"; nocase; endswith; '
                f'sid:{sid}; rev:1; classtype:bad-unknown; metadata:arguscti;)'
            )
            lines.append(sur)
            # Snort 2.9.x has no `dns.query` sticky buffer; the byte-match
            # equivalent is emitted (same packet, raw DNS name).
            snort.append(
                f'alert udp $HOME_NET any -> any 53 '
                f'(msg:"Argus CTI - known malicious domain {value}"; '
                f'content:"{value}"; nocase; sid:{sid}; rev:1; '
                f'classtype:bad-unknown;)'
            )

        elif itype == "url":
            if "://" not in value:
                value = "http" + ("s" if value.startswith("https") else "") + "://" + value
            if not value.startswith("http"):
                value = "http://" + value
            has_net = True
            sid = _sid(f"url-{value}")
            lines.append(
                f'alert http $HOME_NET any -> any any '
                f'(msg:"Argus CTI - known malicious URL"; '
                f'http.uri; content:"{value}"; nocase; '
                f'sid:{sid}; rev:1; classtype:trojan-activity; metadata:arguscti;)'
            )
            snort.append(
                f'alert http $HOME_NET any -> any any '
                f'(msg:"Argus CTI - known malicious URL"; '
                f'content:"{value}"; nocase; '
                f'sid:{sid}; rev:1; classtype:trojan-activity;)'
            )

        elif itype == "ja3":
            if not _HEX.match(value):
                continue
            has_net = True
            sid = _sid(f"ja3-{value}")
            lines.append(
                f'alert tls $HOME_NET any -> any any '
                f'(msg:"Argus CTI - known malicious JA3 {value}"; '
                f'ja3.hash; content:"{value}"; '
                f'sid:{sid}; rev:1; classtype:trojan-activity; metadata:arguscti;)'
            )
            snort.append(_note("note", "JA3 is not a Snort 2.9 keyword; omitted."))

        elif itype in ("md5", "sha1", "sha256"):
            if not _HEX.match(value):
                continue
            file_hashes[itype].append(value)

    # File-hash rules use the list-reference form (Suricata syntax) + the list.
    for htype, values in file_hashes.items():
        if not values:
            continue
        key = f"argus_{htype}.{htype}"
        sid = _sid(f"{htype}-{' '.join(values)}")
        lines.append(
            f'alert http any any -> any any '
            f'(msg:"Argus CTI - known malicious file ({htype})"; '
            f'file{htype}:{key}; filestore; sid:{sid}; rev:1;)'
        )
        # Machine-parseable companion block: the /validate endpoint materialises
        # these into the engine's default-rule-path so `suricata -T` can check
        # the rule with its referenced list present.
        lines.append(f"# [file] companion hash list `{key}`:")
        lines.append(f"#   {values[0]}")
        snort.append(_note("note", f"file hash {htype}: add the value(s) to the "
                                   f"Snort hash list referenced by file{htype}:{key};"))

    if not (has_net or file_hashes):
        note = _note("note", "No network-mappable IOcs; hash-based detection is "
                             "best expressed in the generated YARA rule.")
        lines.append(note)
        snort.append(note)

    return "\n".join(lines).rstrip() + "\n", "\n".join(snort).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# ModSecurity                                                                 #
# --------------------------------------------------------------------------- #

def _modsecurity_rules(iocs: list[dict[str, str]]) -> str:
    lines: list[str] = [
        _note("draft", "ModSecurity rules (OWASP CRS compatible) — " + DISCLAIMER)
    ]
    wrote = False
    for ioc in iocs:
        itype = str(ioc.get("type", "")).lower()
        value = str(ioc.get("value", "")).strip()
        if not value:
            continue
        rid = f"4{sid_base_safe(_sid(f'modsec-{itype}-{value}'))}"
        if itype in ("ipv4", "ipv6") and _IPV4.match(value):
            if itype == "ipv6" and ":" not in value:
                continue
            escaped = re.escape(value)
            lines.append(
                f'SecRule REMOTE_ADDR "@ipMatch {value}" '
                f'"id:{rid},phase:1,deny,status:403,'
                f"msg:'Argus CTI - known malicious IP {value}',"
                f"tag:'argus-cti',tag:'ioc'\")"
            )
            wrote = True
        elif itype == "domain" and _DOMAIN.match(value):
            lines.append(
                f'SecRule REQUEST_HEADERS:Host "@rx ^(.*\\.)?{re.escape(value)}$" '
                f'"id:{rid},phase:1,deny,status:403,'
                f"msg:'Argus CTI - known malicious domain {value}',"
                f"tag:'argus-cti',tag:'ioc'\")"
            )
            wrote = True
        elif itype == "url" and "://" in value:
            escaped = re.escape(value)
            lines.append(
                f'SecRule REQUEST_URI "@rx {escaped}" '
                f'"id:{rid},phase:2,deny,status:403,'
                f"msg:'Argus CTI - known malicious URL {value}',"
                f"tag:'argus-cti',tag:'ioc'\")"
            )
            wrote = True
    if not wrote:
        lines.append(_note("note", "File hashes / JA3 have no ModSecurity "
                                   "equivalent; omitted."))
    return "\n".join(lines).rstrip() + "\n"


def sid_base_safe(sid: int) -> int:
    """Valid ModSecurity rule-id range (1..999999999, no leading zero)."""
    return sid % 900_000_000 + 100_000_000


# --------------------------------------------------------------------------- #
# Firewall / blocklist                                                        #
# --------------------------------------------------------------------------- #

def _firewall_rules(iocs: list[dict[str, str]]) -> dict[str, str]:
    ips = [str(i["value"]).strip() for i in iocs
           if str(i.get("type", "")).lower() in ("ipv4", "ipv6")
           and (_IPV4.match(str(i["value"]).strip()) or
                ("." not in str(i["value"]).strip() and ":" in str(i["value"]).strip()))]
    ips = sorted(set(ips))
    if not ips:
        return {
            "plain": "# No IP indicators -> nothing to block at the firewall level.\n",
            "iptables": "# No IP indicators -> nothing to block at the firewall level.\n",
            "nftables": "# No IP indicators -> nothing to block at the firewall level.\n",
        }
    plain = "".join(f"{ip}\n" for ip in ips)
    ipt = "".join(f"iptables -I INPUT -s {ip} -j DROP  # Argus CTI draft IOC\n"
                  for ip in ips)
    nft = "".join(f"nft add rule inet filter input ip saddr {ip} drop  # Argus CTI draft\n"
                  for ip in ips)
    return {"plain": plain, "iptables": ipt, "nftables": nft}


# --------------------------------------------------------------------------- #
# YARA (from a confirmed-malicious sample / its hashes)                       #
# --------------------------------------------------------------------------- #

def _yara_rule(sample: dict[str, Any] | None, iocs: list[dict[str, str]]) -> str:
    ref = "sample" if sample else "indicator"
    sha = (sample or {}).get("sha256") or next(
        (i["value"] for i in iocs
         if str(i.get("type", "")).lower() == "sha256"), None)
    m5 = (sample or {}).get("md5") or next(
        (i["value"] for i in iocs
         if str(i.get("type", "")).lower() == "md5"), None)
    if not sha:
        return _note("note", "YARA rule generation requires a sample or its "
                             "SHA-256 fingerprint.")
    name = "ArgusCTI_Sample_" + (sha[:12] or "unknown")
    head = [
        _note("draft", "YARA rule — " + DISCLAIMER, prefix="//"),
        'import "hash"',
        "",
        f"rule {name} {{",
        "    meta:",
        f'        description = "Argus CTI - flagged sample {sha[:16]}..."',
        f'        sha256 = "{sha}"',
        f'        md5 = "{m5 or ""}"',
        '        author = "Argus CTI - generated"',
        '        reference = "argus-cti platform scan"',
        "",
        "    strings:",
    ]
    strings: list[str] = []
    if sample and sample.get("path_data"):
        for i, s in enumerate(_yara_strings(sample["path_data"], limit=4), 1):
            head.append(f'        $s{i} = "{_yara_escape(s)}" ascii')
            strings.append(f"$s{i}")
    elif m5:
        head.append(f'        $md5 = "{m5.lower()}"')
        strings.append("$md5")
    if not strings:
        # No strings extracted: hash-only rule (still a valid static signature).
        head.append("        $any = { 01 }  // placeholder never matches benign data")
        strings = []
    head += ["", "    condition:",]
    if strings:
        head.append(f"        any of them")
    else:
        head.append("        uint16(0) == 0x4D5A and filesize < 50MB")
    head.append("}")
    return "\n".join(head).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# Public entry point                                                          #
# --------------------------------------------------------------------------- #

def generate(sample_meta: dict[str, Any] | None, sample_bytes: bytes | None,
             iocs: list[dict[str, str]]) -> dict[str, Any]:
    """Produce every supported output format for a confirmed-MALICIOUS sample.

    `sample_meta` carries identifiers (sha256/md5/filename). `sample_bytes` is
    the quarantined file content used only to draft YARA strings (never served,
    never executed). `iocs` is the indicator set (hashes always, plus any
    IP/domain/URL the scan surfaced).
    """
    yara_input: dict[str, Any] = dict(sample_meta or {})
    if sample_bytes:
        yara_input["path_data"] = sample_bytes
    suricata, snort = _suricata_snort_rules(yara_input, iocs)
    modsec = _modsecurity_rules(iocs)
    firewall = _firewall_rules(iocs)
    yara = _yara_rule(yara_input, iocs)
    return {
        "disclaimer": DISCLAIMER,
        "generated_at_utc": None,  # filled by the router
        "suricata": suricata,
        "snort": snort,
        "modsecurity": modsec,
        "firewall": firewall,
        "yara": yara,
        "validated_with": "suricata -T (Suricata 7 parser; Snort validated "
                          "through the same syntax-compatible subset — Snort 2.9 "
                          "is not installable on the Debian 13 base image)",
    }